#!/usr/bin/env bash

# installs ufw firewall; blocks all incoming traffic except for port 22 ssh, 80 http, 443 https

# install ufw, support both ipv4, ipv6, and ensure default values
sudo apt-get -y install ufw
sudo sed -i ""s/IPV6=no/IPV6=yes/" /etc/default/ufw

sudo ufw default allow outgoing
sudo ufw default deny incoming

#configure
sudo ufw allow ssh
sudo ufw allow http/tcp
sudo ufw allow https/tcp

#start firewall
sudo ufw enable 